### DISCUSSION TITLE
👷 Refactor when to rebuild staging images

### DISCUSSION THREAD

**Discussion by shnizzedy** [FCP-INDI/C-PAC#1754] [Ideas]
### Related problem
The CI is currently set up to check each staging image's Dockerfile for changes and tag for existence before deciding whether to pull or rebuild that stage.

https://github.com/FCP-INDI/C-PAC/blob/12c4f74a3cfeb544239e34301853b90b34d7edc1/.github/workflows/build_stages.yml#L38-L69
https://github.com/FCP-INDI/C-PAC/blob/12c4f74a3cfeb544239e34301853b90b34d7edc1/.github/workflows/build_stages.yml#L72

![screenshot of example run](https://user-images.githubusercontent.com/5974438/177848460-d53ebfbf-8dc4-49a7-a035-8e41a4e59dbd.png)

This logic falls short on both sides of the idea runs-only-when-necessary:

* It has to check for changes every time
* It doesn't catch changes in external sources, e.g., [`c-pac_templates:latest`](https://github.com/FCP-INDI/C-PAC_templates/pkgs/container/c-pac_templates)

### Proposed feature
We could update the CI to take a key string like

```Git
[rebuild AFNI.20.0.04]
``` 

in the commit message, update the strategies to be something like

```YML
    strategy:
      matrix:
        stage:
        - AFNI.16.2.07.neurodocker
        - AFNI.20.0.04
        - ANTs.2.2.0.neurodocker
        - c3d.1.0.0
        - connectome-workbench.1.3.2-1.neurodebian
        - connectome-workbench.1.3.2-2.neurodebian
        - FreeSurfer.6.0.0-min.neurodocker
        - FreeSurfer.6.0.1-min
        - FSL.5.0.9-5.neurodebian
        - FSL.5.0.10
        - ICA-AROMA.0.4.5
        - msm.2.0
```

 and update the workflow logic with something like

```YAML
if: "contains(github.event.head_commit.message, '[rebuild ${{ matrix.stage }}]')"
```

plus some logic to handle which downstream stages depend on a given image. Then rebuilds would

* only happen when a relevant `[rebuild…` is specified
* always happen when a relevant `[rebuild…` is specified

### Alternatives
We could also/additionally add an input parameter to the `workflow_call` so, for example, a merge to [`main`](https://github.com/FCP-INDI/C-PAC_templates/tree/main) in [FCP-INDI/C-PAC_templates](https://github.com/FCP-INDI/C-PAC_templates) could trigger the relevant rebuilds

### Additional context
Ref: [Conditional GitHub action based on commit message](https://dev.to/mliakos/conditional-github-action-based-on-commit-message-2l02)

**Comment by gkiar** [comment]
Cool! In another project, I've handled conditional building like [this](https://github.com/verificarlo/fuzzy/blob/master/.github/workflows/build-fuzzy.yml#L50-L87). It has the perk of not requiring us to be careful with commit messages. I imagine something similar could be done, e.g., with commit messages on things like the template repository. Forgive my ignorance of the current approach, but do you think something like this could work for us?

**Reply by shnizzedy** [reply]
I think this strategy is more or less what's in place now?

<table>
<tr><th>fuzzy</th><th>C-PAC</th></tr>
<tr><td>

[`build-fuzzy.yml#L54-L56`](https://github.com/verificarlo/fuzzy/blob/02484cb732f5fc5801dde4e16f71fe93a88fecbd/.github/workflows/build-fuzzy.yml#L54-L56)

```YAML
      - name: Check for file changes
        uses: jitterbit/get-changed-files@v1
        id: changes
```

</td><td>

https://github.com/FCP-INDI/C-PAC/blob/12c4f74a3cfeb544239e34301853b90b34d7edc1/.github/workflows/build_stages.yml#L121-L134

</td></tr>
<tr><td>

[`build-fuzzy.yml#L89`](https://github.com/verificarlo/fuzzy/blob/02484cb732f5fc5801dde4e16f71fe93a88fecbd/.github/workflows/build-fuzzy.yml#L89)

```YAML
        if: contains(steps.changes.outputs.all, ${{ env.RUN_IF_CHANGED }})
```

</td><td>

https://github.com/FCP-INDI/C-PAC/blob/12c4f74a3cfeb544239e34301853b90b34d7edc1/.github/workflows/build_stages.yml#L236

</td></tr>
</table>

It looks to me like the differences here are fairly superficial:
* fuzzy has 2 tiers of stages; C-PAC has 4
* the workflows use different marketplace actions to check for file changes
* fuzzy's strategy implicitly differentiates between "fork point" and "last commit"; C-PAC's strategy does so implicitly
* fuzzy only rebuilds the final stage if [that repo's `docker` directory](https://github.com/verificarlo/fuzzy/tree/master/docker) has changes; C-PAC rebuild the final stage every time

Am I missing something?

---

> not requiring us to be careful with commit messages

Is the concern that we'd update a Dockerfile but forget to rebuild it? I hadn't thought of that, but we could combine approaches here and add the proposed strategy here to the existing strategy instead of replacing it. (I.e, rebuild if the `[rebuild…` key is given OR the relevant Dockerfile changed)
