### ISSUE TITLE
Benchmark C-PAC against fmriprep+XCP outputs

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1141]

**Comment by sgiavasis** [comment]
Just need to bundle C-PAC with this preconfig now.

**Comment by sgiavasis** [comment]
I believe @hahaai has the config ready - @SucyLi or @HechengJin0 could we just place it into the [/resources/configs](https://github.com/FCP-INDI/C-PAC/tree/develop/CPAC/resources/configs) list in resources and make a PR to `develop`?

**Comment by hahaai** [comment]
@sgiavasis @SucyLi  I don't have one for 1.8. The CPAC:F/X option is basically the CPAC:fMRIPrep + the following nuisance regression and filter.
# Select which nuisance signal corrections to apply
```
Regressors:
- Bandpass:
    bottom_frequency: 0.01
    top_frequency: 0.08
  CerebrospinalFluid:
    erode_mask: false
    extraction_resolution: 2
    include_delayed: true
    include_delayed_squared: true
    include_squared: true
    summary: Mean
  GlobalSignal:
    include_delayed: true
    include_delayed_squared: true
    include_squared: true
    summary: Mean
  Motion:
    include_delayed: true
    include_delayed_squared: true
    include_squared: true
  WhiteMatter:
    erode_mask: false
    extraction_resolution: 2
    include_delayed: true
    include_delayed_squared: true
    include_squared: true
    summary: Mean
  PolyOrt: 
    degree: 2


# Whether to run frequency filtering before or after nuisance regression.
# ['Before'] or ['After']
filtering_order: ['After']
```
