### ISSUE TITLE
Potential crashes when supplying brain mask in data config

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1259]
When using the **brain_mask** key in the data config like so:

```
    subject_id: sub02
    unique_id: ses02
    anat: /path/to/site01/sub02/ses02/anatomical.nii.gz
    brain_mask: /path/to/site01/sub02/ses02/brain-mask.nii.gz
    creds_path: None
    func:
      scan_1:
        scan: /path/to/site01/sub02/ses02/scan_1_func.nii.gz
        scan_parameters: None
    site: site01
```
