### ISSUE TITLE
🐛 Custom pipeline config file is modified during execution

### ISSUE THREAD

**Issue by tbweng** [FCP-INDI/C-PAC#1497]
**Describe the bug**

C-PAC execution seems to modify the pipeline config file that is passed in to the `--pipeline_config` argument. Perhaps the custom pipeline config is being merged somehow with the default pipeline. Specifically, the time series extraction and seed correlation portion.

**To Reproduce**

1. Modify default pipeline config for Dual Regression only using the PNAS_Smith09_rsn10.nii.gz atlas.

```
  tse_roi_paths:
    /cpac_templates/PNAS_Smith09_rsn10.nii.gz: SpatialReg

  sca_roi_paths:
    /cpac_templates/PNAS_Smith09_rsn10.nii.gz: DualReg
```

2. Run C-PAC with custom pipeline config file using `--pipeline_config` argument.
3. Review the pipeline config file in the output dir.
4. See the default atlases/rois have populated the `tse_roi_paths` and `sca_roi_paths`

**Expected behavior**

only run tse and sca for the atlases/rois in the custom pipeline config file.

**Versions** 
 - C-PAC: 1.8.0 
 - Container Platform :
    - Singularity: 3.7.0-1.el7

**Comment by shnizzedy** [comment]
> Perhaps the custom pipeline config is being merged somehow with the default pipeline.

You're correct:

> If you want to base a pipeline on another pipeline configuration YAML file, you can specify
>
> ```YAML
> FROM: /path/to/pipeline.yml
> ```
> in your pipeline configuration file. You can use the name of a [preconfigured pipeline](https://fcp-indi.github.io/docs/latest/user/pipelines/preconfig) instead of a filepath if you want to base a configuration file on a preconfigured pipeline. If `FROM` is not specified, the pipeline will be based on [the default pipeline](https://fcp-indi.github.io/docs/latest/user/pipelines/default).

― [C-PAC User Guide: Setting Up A Pipeline Configuration § Using a Text Editor](https://fcp-indi.github.io/docs/latest/user/pipelines/pipeline_config#using-a-text-editor)

The idea here is that you can specify only what you want different from the default pipeline config (or whatever config you specify with the `FROM` key). (So if, for example you wanted to run the default pipeline config except with all three available analyses for , this would be a complete pipeline configuration to do so:

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    /cpac_templates/PNAS_Smith09_rsn10.nii.gz: Avg, DualReg, MultReg
```

You've identified a design oversight present in v1.8.0: that a user would want to exclude keys present in the default configuration (specifically the `*_roi_paths` keys).

We'll include a fix for this issue in an upcoming release, and I'll @ you when we have a development container with the fix.

In the meantime, you can either run with the ROI paths you want plus the ones included in the default pipeline, or you can try to do your analyses with the previous C-PAC release (v1.7.2), which has a different pipeline configuration syntax:

* [C-PAC v1.7.2 User Guide: Preconfigured Pipelines § default: The Default Pipeline](https://fcp-indi.github.io/docs/v1.7.2/user/preconfig#default-the-default-pipeline)
* [C-PAC v1.7.2 User Guide: Setting Up A Pipeline Configuration § Using a Text Editor](https://fcp-indi.github.io/docs/v1.7.2/user/pipeline_config#using-a-text-editor)

**Comment by shnizzedy** [comment]
@FCP-INDI/developers I've been thinking about this issue and there are multiple scenarios we need to consider in the design of the fix here. I've got a few design ideas sketched out below. I'd love your thoughts (you can click on the chart to vote). Also, if you like design 3, please suggest a key / value and default.

[![](https://api.gh-polls.com/poll/01F4CHEXWQNJP06RABKXD5141X/Design%201)](https://api.gh-polls.com/poll/01F4CHEXWQNJP06RABKXD5141X/Design%201/vote)
[![](https://api.gh-polls.com/poll/01F4CHEXWQNJP06RABKXD5141X/Design%202)](https://api.gh-polls.com/poll/01F4CHEXWQNJP06RABKXD5141X/Design%202/vote)
[![](https://api.gh-polls.com/poll/01F4CHEXWQNJP06RABKXD5141X/Design%203)](https://api.gh-polls.com/poll/01F4CHEXWQNJP06RABKXD5141X/Design%203/vote)
[![](https://api.gh-polls.com/poll/01F4CHEXWQNJP06RABKXD5141X/Design%201%20+%202)](https://api.gh-polls.com/poll/01F4CHEXWQNJP06RABKXD5141X/Design%201%20+%202/vote)
[![](https://api.gh-polls.com/poll/01F4CHEXWQNJP06RABKXD5141X/Design%202%20+%203)](https://api.gh-polls.com/poll/01F4CHEXWQNJP06RABKXD5141X/Design%202%20+%203/vote)
[![](https://api.gh-polls.com/poll/01F4CHEXWQNJP06RABKXD5141X/other)](https://api.gh-polls.com/poll/01F4CHEXWQNJP06RABKXD5141X/other/vote)


# Scenarios
The examples here are just describing <span title="seed-based correlation anlaysis">SCA</span>; the same strategy would also apply to <span title="timeseries extraction">TSE</span>.
## Scenario 1: Choose different analyses for default <span title="regions of interest">ROIs</span>
### Example
Do all 3 SCA analyses on `PNAS_Smith09_rsn10`. Otherwise do default analyses on default ROIs.
## Scenario 2: Choose new (additional) ROIs
### Example
Add `custom_roi` with `DualReg` SCA analysis to default SCA ROIs.
## Scenario 3: Choose new (replacement) ROIs
### Example
Do only `custom_roi` with `DualReg` SCA analysis for SCA
## Scenario 4: Subset default ROIs
### Example
Do only `DualReg` for `PNAS_Smith09_rsn10` for SCA and no other ROIs

# Designs
## Design 1: If any ROIs are specified, ROIs must be fully specified
## Design 2: ROIs can be set empty to remove them
This one isn't mutually-exclusive with the other designs.
## Design 3: Add a config key under `tse_roi_paths` and `sca_roi_paths` to let users specify whether the configuration is an update or a replacement
This design is the only one of the three that can be few lines regardless of the scenario, but I'm not sold on the clarity of any of my key/value ideas:
* `replace: boolean` (default `false`)
* `replacement: boolean` (default `false`)
* `update: boolean` (default `true`)

In the example configs below, I'm using `update`.

# Example configs
Here's how each of the scenarios could be accomplished with each of the designs.

<table>
<tr>
<th>design →</th><th rowspan="2">1</th><th rowspan="2">2</th><th rowspan="2">3</th>
</tr>
<tr>
<th><sub>scenario ↓</th>
</tr>
<tr>
<th>1</th><td>

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    /cpac_templates/PNAS_Smith09_rsn10.nii.gz: Avg, DualReg, MultReg
    /cpac_templates/CC400.nii.gz: Avg, MultReg
    /cpac_templates/ez_mask_pad.nii.gz: Avg, MultReg
    /cpac_templates/aal_mask_pad.nii.gz: Avg, MultReg
    /cpac_templates/CC200.nii.gz: Avg, MultReg
    /cpac_templates/tt_mask_pad.nii.gz: Avg, MultReg
    /cpac_templates/ho_mask_pad.nii.gz: Avg, MultReg
    /cpac_templates/rois_3mm.nii.gz: Avg, MultReg
```
</td><td>

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    /cpac_templates/PNAS_Smith09_rsn10.nii.gz: Avg, DualReg, MultReg
```
</td><td>

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    /cpac_templates/PNAS_Smith09_rsn10.nii.gz: Avg, DualReg, MultReg
```

or

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    update: true
    /cpac_templates/PNAS_Smith09_rsn10.nii.gz: Avg, DualReg, MultReg
```
</td>

</tr><tr>
<th>2</th><td>

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    /cpac_templates/PNAS_Smith09_rsn10.nii.gz: DualReg
    /cpac_templates/CC400.nii.gz: Avg, MultReg
    /cpac_templates/ez_mask_pad.nii.gz: Avg, MultReg
    /cpac_templates/aal_mask_pad.nii.gz: Avg, MultReg
    /cpac_templates/CC200.nii.gz: Avg, MultReg
    /cpac_templates/tt_mask_pad.nii.gz: Avg, MultReg
    /cpac_templates/ho_mask_pad.nii.gz: Avg, MultReg
    /cpac_templates/rois_3mm.nii.gz: Avg, MultReg
    /path/to/custom_roi.nii.gz: DualReg
```
</td><td>

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    /path/to/custom_roi.nii.gz: DualReg
```
</td><td>

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    /path/to/custom_roi.nii.gz: DualReg
```

or

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    update: true
    /path/to/custom_roi.nii.gz: DualReg
```
</td>
</tr><tr>
<th>3</th>
<td>

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    /path/to/custom_roi.nii.gz: DualReg
```
</td><td>

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    /cpac_templates/PNAS_Smith09_rsn10.nii.gz:
    /cpac_templates/CC400.nii.gz:
    /cpac_templates/ez_mask_pad.nii.gz:
    /cpac_templates/aal_mask_pad.nii.gz:
    /cpac_templates/CC200.nii.gz:
    /cpac_templates/tt_mask_pad.nii.gz:
    /cpac_templates/ho_mask_pad.nii.gz:
    /cpac_templates/rois_3mm.nii.gz:
    /path/to/custom_roi.nii.gz: DualReg
```
</td><td>

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
   update: false
    /path/to/custom_roi.nii.gz: DualReg
```
</td>
</tr><tr>
<th>4</th><td>

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    /cpac_templates/PNAS_Smith09_rsn10.nii.gz: DualReg
```
</td><td>

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    /cpac_templates/PNAS_Smith09_rsn10.nii.gz: DualReg
    /cpac_templates/CC400.nii.gz:
    /cpac_templates/ez_mask_pad.nii.gz:
    /cpac_templates/aal_mask_pad.nii.gz:
    /cpac_templates/CC200.nii.gz:
    /cpac_templates/tt_mask_pad.nii.gz:
    /cpac_templates/ho_mask_pad.nii.gz:
    /cpac_templates/rois_3mm.nii.gz:
```
</td><td>

```YAML
seed_based_correlation_analysis:
  sca_roi_paths:
    update: false
    /cpac_templates/PNAS_Smith09_rsn10.nii.gz: DualReg
```
</td>
</tr>
</table>
