### ISSUE TITLE
🐛 XCP QC needs DVARS

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1655]
### Describe the bug

It throws up without it:

```Python
LookupError: When trying to connect node block 'qc_xcp_native' to workflow 'cpac_0050642_ses-1' after node block 'qc_xcp_skullstripped': 

[!] C-PAC says: The listed resource is not in the resource pool:
dvars

Developer Note: This may be due to a mismatch between the node block's docstring 'input' field and a strat_pool.get_data() call within the block function.
(keys in resource pool are dict_keys(['json', 'bold', 'subject', 'scan', 'T1w', 'max-displacement', 'desc-preproc_bold', 'desc-preproc_T1w', 'space-T1w_desc-mean_bold', 'space-bold_desc-brain_mask', 'movement-parameters', 'rels-displacement', 'coordinate-transformation']))
```

### To reproduce

Run with this pipeline config:

```YAML
FROM: abcd-options
pipeline_setup:
  pipeline_name: ABCD-blip
  Debugging:
    verbose: On
  output_directory:
    quality_control:
      generate_xcpqc_files: On
functional_preproc:
  distortion_correction:
    using:
      - PhaseDiff
      - Blip
```

### Expected behavior

XCP-QC just doesn't include DVARS if values are missing

### Acceptance criteria

C-PAC doesn't crash if xcpqc is on without DVARs in resource pool

### C-PAC version

v1.8.3-dev

### Container platform

Docker
