### ISSUE TITLE
🐛 Job hangs after completion

### ISSUE THREAD

**Issue by gkiar** [FCP-INDI/C-PAC#1681]
### Describe the bug

My CPAC run didn't "exit" after completing, so jobs on the scheduler were left running and consuming resources beyond the lifetime of the job. When looking at the standard out, we can see:

```
Pipeline configuration: cpac-default-pipeline
        Subject workflow: cpac_sub-A00077183_ses-BAS1
        Elapsed run time (minutes): 717.9533566435178
        Timing information saved in /ocean/projects/cis210040p/shared/NKI-RS/dataset_4subs/derivatives_default_ieee/eval-0/log/cpac_individual_timing_cpac-default-pipeline.csv
        System time of start:      2022-02-15 17:15:37
        System time of completion: 2022-02-16 05:13:31
```

However, at the same time, I look at the status of my running job, and find the following:

```
6724008        23:00:00 2022-02-15T17:15:02   14:57:25    RUNNING  RM-shared         15     2000Mc 
6724008.bat+            2022-02-15T17:15:02   14:57:25    RUNNING                    15     2000Mc 
6724008.ext+            2022-02-15T17:15:02   14:57:25    RUNNING                    15     2000Mc 
```

Which shows that it is still running, and has been for approximately 3 hours since the job supposedly completed.

I launched C-PAC with the following config:
```
%YAML 1.1
---
# CPAC Pipeline Configuration YAML file
# Version 1.8.2
#
# http://fcp-indi.github.io for more info.
#
# Pipeline config "Default", version GUI-0
# Fri Dec 10 2021 15:50:24 GMT-0500 (Eastern Standard Time)
#
# Tip: This file can be edited manually with a text editor for quick modifications.

FROM: default

pipeline_setup:
  system_config:
    num_ants_threads: 3
    num_OMP_threads: 3
    num_participants_at_once: 4
  Debugging:
    verbose: true

```

### To reproduce

Hard to say with precision, but what I did was as follows:

1. Go on the PSC SuperComputing Cluster
2. Download the v1.8.3 container into Singularity
3. Patch the `bids_utils.py` file on runtime by binding the new version from `develop` to the correct location
4. Run the tool as follows:

```
singularity run \
      -B <some data mounts> \
      -B ~/code/C-PAC/CPAC/utils/bids_utils.py:/code/CPAC/utils/bids_utils.py \
      ~/shared_data/singularity_images/fuzzy-cpac-1.8.3.sif \
      </indata> \
      </outdata> \
      participant \
      --save_working_dir \
      --skip_bids_validator \
      --pipeline_file config-default.yml \
      --n_cpus 15 \
      --mem_gb 30
```

### Expected behavior

That the task would complete upon completion of the pipeline.

### Acceptance criteria

- [ ] The expected behaviour :upside_down_face: 

### C-PAC version

v1.8.3

### Container platform

Singularity

### Docker and/or Singularity version(s)

Singularity 3.8.0-1.el8

### Additional context

An aside, this was being run on 4 subjects. It's interesting to look at the efficiency of the workflow and find that we did reach our memory limits, but in general we were computationally a bit wasteful. I think this is largely because many of the steps are single threaded but require lots of memory. Perhaps with more subjects this would be improved, as while things are waiting at RAM bottlenecks, computation could continue elsewhere.

```
$ seff 6724008
Job ID: 6724008
Cluster: bridges2
User/Group: gkiar/cis210040p
State: CANCELLED (exit code 0)
Nodes: 1
Cores per node: 15
CPU Utilized: 2-18:33:54
CPU Efficiency: 29.65% of 9-08:31:00 core-walltime
Job Wall-clock time: 14:58:04
Memory Utilized: 28.32 GB
Memory Efficiency: 96.68% of 29.30 GB
```
