### ISSUE TITLE
🐛  desc-restore_T1w not in resource pool when running post_freesurfer on ccs pipeline

### ISSUE THREAD

**Issue by amygutierrez** [FCP-INDI/C-PAC#1694]
### Describe the bug

Whenever you turn `post_freesurfer: run: On` in the ccs pipeline or default pipeline config, the error below appears: 
```
LookupError: When trying to connect node block 'surface_preproc' to workflow 'cpac_sub-1019436_ses-1' after node block 'transform_deriv_mask_to_EPItemplate': 
[!] C-PAC says: The listed resource is not in the resource pool:
LookupError: When trying to connect node block 'surface_preproc' to workflow 'cpac_sub-1019436_ses-1' after node block 'transform_deriv_mask_to_EPItemplate': 
[!] C-PAC says: The listed resource is not in the resource pool:
desc-restore_T1w
```

This is basically saying that `desc-restore_T1w` is not in the resource pool. `desc-restore_T1w` is only present as an output from [freesurfer_abcd_preproc](https://github.com/FCP-INDI/C-PAC/blob/80424468c7f4e59c102f446b05d4154ec1cd4b2d/CPAC/anat_preproc/anat_preproc.py#L3020-L3037) and freesurfer_abcd_preproc is not used when running freesurfer from the [css-pipeline](https://github.com/FCP-INDI/C-PAC/blob/80424468c7f4e59c102f446b05d4154ec1cd4b2d/CPAC/resources/configs/pipeline_config_ccs-options.yml#L82) because the css pipeline uses `'FreeSurfer-BET-Tight` or `'FreeSurfer-BET-Loose'`. 

### To reproduce

1. Amend CSS pipeline to run with `post_freesurfer`:

```
## PIPELINE FILE ##
# CPAC Pipeline Configuration YAML file
# Version 1.8.1
#
# http://fcp-indi.github.io for more info.
#
# Tip: This file can be edited manually with a text editor for quick modifications.
FROM: ccs-options
pipeline_setup: 
  pipeline_name: ccs_post_freesurfer
  output_directory: 
    path: /output/output
  working_directory: 
    path: /output/working
    remove_working_dir: Off
  log_directory: 
    path: /output/log
surface_analysis: 
  # Will run Freesurfer for surface-based analysis. Will output traditional Freesurfer derivatives.
  # If you wish to employ Freesurfer outputs for brain masking or tissue segmentation in the voxel-based pipeline,
  # select those 'Freesurfer-' labeled options further below in anatomical_preproc.
  freesurfer: 
    
    run: On
    
  post_freesurfer: 
    run: On
```

2. Run cpac from `develop` branch using any subject dataset. Use the amended pipeline from step 1 as the `--pipeline_file` in the docker command. Docker run command example: 

```
docker run --security-opt=apparmor:unconfined -v /home/{username}/Documents/C-PAC:/code -v /home/{username}/Documents/C-PAC/dev/docker_data/run.py:/code/run.py -v /home/{username}/Documents/C-PAC/dev/docker_data/run-with-freesurfer.sh:/code/run-with-freesurfer.sh -v /home/{username}/Documents/C-PAC/dev/docker_data/default_pipeline.yml:/cpac_resources/default_pipeline.yml -v /home/{username}/Documents/C-PAC/edited_pipelines/ccs_post_freesurfer.yml:/ccs_post_freesurfer.yml -v /data3/cnl/{username}/connectome_bootcamp/ccs_pipeline:/output fcpindi/c-pac:nightly s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/KKI /output participant --save_working_dir --skip_bids_validator --n_cpus 1 --mem_gb 15 --participant_label sub-1019436 --pipeline_file /ccs_post_freesurfer.yml
 ```

### Expected behavior

After executing the Docker run, there should be an error that says:
```
LookupError: When trying to connect node block 'surface_preproc' to workflow 'cpac_sub-1019436_ses-1' after node block 'transform_deriv_mask_to_EPItemplate': 
[!] C-PAC says: The listed resource is not in the resource pool:
desc-restore_T1w
Developer Note: This may be due to a mismatch between the node block's docstring 'input' field and a strat_pool.get_data() call within the block function.
(keys in resource pool are dict_keys(['json', 'freesurfer-subject-dir', 'from-T1w_to-template_mode-image_xfm']))
```

### Acceptance criteria

Error no longer appears and cpac run completes cleanly. Post_freesurfer folder should be in the working directory.
