### ISSUE TITLE
🐛 Templates don't match between `monkey` and `nhp-macaque`

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1699]
### monkey
```YAML
anatomical_preproc:
  acpc_alignment:
    FOV_crop: flirt
    T1w_brain_ACPC_template: /cpac_templates/MacaqueYerkes19_T1w_0.5mm_brain.nii.gz
    T2w_ACPC_template: /cpac_templates/MacaqueYerkes19_T2w_0.5mm.nii.gz
    T2w_brain_ACPC_template: /cpac_templates/MacaqueYerkes19_T2w_0.5mm_brain.nii.gz
voxel_mirrored_homotopic_connectivity:
 symmetric_registration:
    T1w_brain_template_symmetric_for_resample: /cpac_templates/resources/MacaqueYerkes19_T1w_1.0mm.nii.gz
```

### nhp-macaque
```YAML
anatomical_preproc:
  acpc_alignment:
    FOV_crop: robustfov
    T1w_brain_ACPC_template: /usr/share/fsl/5.0/data/standard/MNI152_T1_1mm_brain.nii.gz
    T2w_ACPC_template:
    T2w_brain_ACPC_template:
voxel_mirrored_homotopic_connectivity:
  symmetric_registration:
    T1w_brain_template_symmetric_for_resample: /cpac_templates/MacaqueYerkes19_T1w_1.0mm.nii.gz
```

### Expected behavior

Either match the templates or document the intentional differences

### Acceptance criteria

- [ ] match the templates or document the intentional differences

### C-PAC version

v1.8.2, v1.8.3
