### ISSUE TITLE
🐛 Pipeline hanging at `Connecting ReHo...` when forking `motion_correct_reference`

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1732]
### Describe the bug

With 
```YAML
functional_preproc:
  motion_estimates_and_correction:
    motion_correction:
      motion_correction_reference:
        - mean
        - median
regional_homogeneity:
  run: On
```

Pipeline hangs at
```BASH
Connecting ReHo...
```

### To reproduce

Run with [pipeline_config_rbc-options.yml@`d231730`](https://github.com/FCP-INDI/C-PAC/blob/d231730dc2f32fae87d18899dc5cf3e3a8ee18df/CPAC/resources/configs/pipeline_config_rbc-options.yml) ([expanded_pipeline_config.yml](https://github.com/FCP-INDI/C-PAC/files/8730402/expanded_pipeline_config.yml.txt))
 

### Expected behavior

C-PAC forks at motion correction reference and outputs all expected outputs for each reference

### Acceptance criteria

- [ ] expected behavior
    OR
- [ ] `motion_correct_reference` is not forkable

### C-PAC version

v1.8.4-dev @ d231730dc2f32fae87d18899dc5cf3e3a8ee18df

### Container platform

Singularity

### Docker and/or Singularity version(s)

3.8.5-2.el7
