### ISSUE TITLE
🐛 `create_nuisance_regression_workflow`: `TypeError: 'NoneType' object is not subscriptable`

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1979]
### Describe the bug

```Python
Traceback (most recent call last):
  File "/code/run.py", line 807, in <module>
    run_main()
  File "/code/run.py", line 788, in run_main
    test_config=(1 if args.analysis_level == "test_config" else 0)
  File "/code/CPAC/pipeline/cpac_runner.py", line 583, in run
    raise e
  File "/code/CPAC/pipeline/cpac_runner.py", line 580, in run
    p_name, plugin, plugin_args, test_config)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 443, in run_workflow
    subject_id, sub_dict, c, p_name, num_ants_cores
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 1376, in build_workflow
    wf = connect_pipeline(wf, cfg, rpool, pipeline_blocks)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 1064, in connect_pipeline
    wf = nb.connect_block(wf, cfg, rpool)
  File "/code/CPAC/pipeline/engine.py", line 1277, in connect_block
    pipe_x, opt)
  File "/code/CPAC/nuisance/nuisance.py", line 2326, in nuisance_regression
    nuis = create_nuisance_regression_workflow(opt, name='nuisance_regression'
TypeError: 'NoneType' object is not subscriptable
```

### To reproduce

1. Run a pipeline with a regressor on a set of participants
2. Run that same pipeline on a superset of participants containing the original participants and pointing to the same output and working directories
3. See error

### Preconfig

- [ ] default
- [ ] abcd-options
- [ ] anat-only
- [ ] blank
- [ ] ccs-options
- [ ] fmriprep-options
- [ ] fx-options
- [ ] monkey
- [ ] monkey-ABCD
- [ ] ndmg
- [ ] nhp-macaque
- [ ] preproc
- [ ] rbc-options
- [ ] rodent

### Custom pipeline configuration

<details><summary><code>pipeline_config_cpac_1.8.4_36P_motion_EDITED.yml</code></summary>

```YAML
%YAML 1.1
---
# CPAC Pipeline Configuration YAML file
# Version 1.8.4
#
# http://fcp-indi.github.io for more info.
#
# Tip: This file can be edited manually with a text editor for quick modifications.
FROM: default

pipeline_setup: 
  pipeline_name: cpac_36P_motionp

  working_directory: 
    # Deletes the contents of the Working Directory after running.
    # This saves disk space, but any additional preprocessing or analysis will have to be completely re-run.
    remove_working_dir: Off

  system_config: 
    # Select Off if you intend to run CPAC on a single machine.
    # If set to On, CPAC will attempt to submit jobs through the job scheduler / resource manager selected below.
    on_grid: 
      SGE: 
        # SGE Parallel Environment to use when running CPAC.
        # Only applies when you are running on a grid or compute cluster using SGE.
        parallel_environment: cpac

    # The maximum amount of memory each participant's workflow can allocate.
    # Use this to place an upper bound of memory usage.
    # - Warning: 'Memory Per Participant' multiplied by 'Number of Participants to Run Simultaneously'
    #   must not be more than the total amount of RAM.
    # - Conversely, using too little RAM can impede the speed of a pipeline run.
    # - It is recommended that you set this to a value that when multiplied by
    #   'Number of Participants to Run Simultaneously' is as much RAM you can safely allocate.
    num_participants_at_once: 6
    maximum_memory_per_participant: 3

    # Full path to the FSL version to be used by CPAC.
    # If you have specified an FSL path in your .bashrc file, this path will be set automatically.
    FSLDIR: FSLDIR

  Amazon-AWS: 
    # Enable server-side 256-AES encryption on data to the S3 bucket
    s3_encryption: On

anatomical_preproc: 
  non_local_means_filtering:
    run: Off

  # N4 bias field correction via ANTs
  n4_bias_field_correction:
    run: On

  brain_extraction: 

    run: On

    # using: ['3dSkullStrip', 'BET', 'UNet', 'niworkflows-ants', 'FreeSurfer-ABCD', 'FreeSurfer-BET-Tight', 'FreeSurfer-BET-Loose']
    # this is a fork option
    using: [3dSkullStrip]

    # option parameters
    AFNI-3dSkullStrip: 

      # Output a mask volume instead of a skull-stripped volume. The mask volume containes 0 to 6, which represents voxel's postion. If set to True, C-PAC will use this output to generate anatomical brain mask for further analysis.
      mask_vol: Off

      # Set the threshold value controlling the brain vs non-brain voxels. Default is 0.6.
      shrink_factor: 0.62

      # Vary the shrink factor at every iteration of the algorithm. This prevents the likelihood of surface getting stuck in large pools of CSF before reaching the outer surface of the brain. Default is On.
      var_shrink_fac: On

      # The shrink factor bottom limit sets the lower threshold when varying the shrink factor. Default is 0.4, for when edge detection is used (which is On by default), otherwise the default value is 0.65.
      shrink_factor_bot_lim: 0.42

      # Avoids ventricles while skullstripping.
      avoid_vent: On

      # Set the number of iterations. Default is 250.The number of iterations should depend upon the density of your mesh.
      n_iterations: 252

      # While expanding, consider the voxels above and not only the voxels below
      pushout: On

      # Perform touchup operations at the end to include areas not covered by surface expansion.
      touchup: On

      # Give the maximum number of pixels on either side of the hole that can be filled. The default is 10 only if 'Touchup' is On - otherwise, the default is 0.
      fill_hole: 10

      # Perform nearest neighbor coordinate interpolation every few iterations. Default is 72.
      NN_smooth: 74

      # Perform final surface smoothing after all iterations. Default is 20.
      smooth_final: 22

      # Avoid eyes while skull stripping. Default is On.
      avoid_eyes: On

      # Use edge detection to reduce leakage into meninges and eyes. Default is On.
      use_edge: On

      # Speed of expansion.
      exp_frac: 0.1

      # Perform aggressive push to edge. This might cause leakage. Default is Off.
      push_to_edge: Off

      # Use outer skull to limit expansion of surface into the skull in case of very strong shading artifacts. Use this only if you have leakage into the skull.
      use_skull: Off

      # Percentage of segments allowed to intersect surface. It is typically a number between 0 and 0.1, but can include negative values (which implies no testing for intersection).
      perc_int: 0

      # Number of iterations to remove intersection problems. With each iteration, the program automatically increases the amount of smoothing to get rid of intersections. Default is 4.
      max_inter_iter: 4

      # Multiply input dataset by FAC if range of values is too small.
      fac: 1

      # Blur dataset after spatial normalization. Recommended when you have lots of CSF in brain and when you have protruding gyri (finger like). If so, recommended value range is 2-4. Otherwise, leave at 0.
      blur_fwhm: 0

      # Set it as True if processing monkey data with AFNI
      monkey: Off

    FSL-BET: 

      # Set the threshold value controling the brain vs non-brain voxels, default is 0.5
      frac: 0.5

      # Mask created along with skull stripping. It should be `On`, if selected functionalMasking :  ['Anatomical_Refined'] and `FSL` as skull-stripping method.
      mask_boolean: On

      # Mesh created along with skull stripping
      mesh_boolean: Off

      # Create a surface outline image
      outline: Off

      # Add padding to the end of the image, improving BET.Mutually exclusive with functional,reduce_bias,robust,padding,remove_eyes,surfaces
      padding: Off

      # Integer value of head radius
      radius: 0

      # Reduce bias and cleanup neck. Mutually exclusive with functional,reduce_bias,robust,padding,remove_eyes,surfaces
      reduce_bias: Off

      # Eyes and optic nerve cleanup. Mutually exclusive with functional,reduce_bias,robust,padding,remove_eyes,surfaces
      remove_eyes: Off

      # Robust brain center estimation. Mutually exclusive with functional,reduce_bias,robust,padding,remove_eyes,surfaces
      robust: Off

      # Create a skull image
      skull: Off

      # Gets additional skull and scalp surfaces by running bet2 and betsurf. This is mutually exclusive with reduce_bias, robust, padding, remove_eyes
      surfaces: Off

      # Apply thresholding to segmented brain image and mask
      threshold: Off

      # Vertical gradient in fractional intensity threshold (-1,1)
      vertical_gradient: 0.0

    UNet: 

      # UNet model
      unet_model: s3://fcp-indi/resources/cpac/resources/Site-All-T-epoch_36.model

    niworkflows-ants: 

      # Template to be used during niworkflows-ants.
      # It is not necessary to change this path unless you intend to use a non-standard template.

      # niworkflows-ants Brain extraction template
      template_path: /ants_template/oasis/T_template0.nii.gz

      # niworkflows-ants probability mask
      mask_path: /ants_template/oasis/T_template0_BrainCerebellumProbabilityMask.nii.gz

      # niworkflows-ants registration mask (can be optional)
      regmask_path: /ants_template/oasis/T_template0_BrainCerebellumRegistrationMask.nii.gz

    FreeSurfer-BET: 

      # Template to be used for FreeSurfer-BET brain extraction in CCS-options pipeline
      T1w_brain_template_mask_ccs: /ccs_template/MNI152_T1_1mm_first_brain_mask.nii.gz

segmentation: 
  tissue_segmentation: 
    # option parameters
    FSL-FAST: 
      use_priors: 
        # Full path to a directory containing binarized prior probability maps.
        # These maps are included as part of the 'Image Resource Files' package available on the Install page of the User Guide.
        # It is not necessary to change this path unless you intend to use non-standard priors.
        priors_path: $FSLDIR/data/standard/tissuepriors/2mm

    Template_Based: 
      # These masks should be in the same space of your registration template, e.g. if
      # you choose 'EPI Template' , below tissue masks should also be EPI template tissue masks.
      #
      # Options: ['T1_Template', 'EPI_Template']
      template_for_segmentation: []

      # These masks are included as part of the 'Image Resource Files' package available
      # on the Install page of the User Guide.

      # Full path to a binarized White Matter mask.
      WHITE: $FSLDIR/data/standard/tissuepriors/2mm/avg152T1_white_bin.nii.gz

      # Full path to a binarized Gray Matter mask.
      GRAY: $FSLDIR/data/standard/tissuepriors/2mm/avg152T1_gray_bin.nii.gz

      # Full path to a binarized CSF mask.
      CSF: $FSLDIR/data/standard/tissuepriors/2mm/avg152T1_csf_bin.nii.gz

registration_workflows: 
  functional_registration: 
    EPI_registration: 
      ANTs: 
        # EPI registration configuration - synonymous with T1_registration
        # parameters under anatomical registration above
        parameters: 
    func_registration_to_template: 
      output_resolution: 
        # The resolution (in mm) to which the preprocessed, registered functional timeseries outputs are written into.
        # NOTE:
        #   selecting a 1 mm or 2 mm resolution might substantially increase your RAM needs- these resolutions should be selected with caution.
        #   for most cases, 3 mm or 4 mm resolutions are suggested.
        # NOTE:
        #   this also includes the single-volume 3D preprocessed functional data,
        #   such as the mean functional (mean EPI) in template space
        func_preproc_outputs: 2mm

        # The resolution (in mm) to which the registered derivative outputs are written into.
        # NOTE:
        #   this is for the single-volume functional-space outputs (i.e. derivatives)
        #   thus, a higher resolution may not result in a large increase in RAM needs as above
        func_derivative_outputs: 2mm

functional_preproc:
  slice_timing_correction: 
    run: [Off]
    # Interpolate voxel time courses so they are sampled at the same time points.
    # this is a fork point
    #   run: [On, Off] - this will run both and fork the pipeline
 
  truncation: 
    # First timepoint to include in analysis.
    # Default is 0 (beginning of timeseries).
    # First timepoint selection in the scan parameters in the data configuration file, if present, will over-ride this selection.
    # Note: the selection here applies to all scans of all participants.
    start_tr: 3

    # Last timepoint to include in analysis.
    # Default is None or End (end of timeseries).
    # Last timepoint selection in the scan parameters in the data configuration file, if present, will over-ride this selection.
    # Note: the selection here applies to all scans of all participants.
    stop_tr: None

  motion_estimates_and_correction: 
    motion_estimates: 
      # calculate motion statistics BEFORE slice-timing correction
      calculate_motion_first: On

  func_masking: 
    # using: ['AFNI', 'FSL', 'FSL_AFNI', 'Anatomical_Refined', 'Anatomical_Based']
    # this is a fork point
    using: [AFNI]

 
nuisance_corrections: 
  2-nuisance_regression: 
    # Select which nuisance signal corrections to apply
    Regressors:
      - Name: 36parameter
        Bandpass:
          bottom_frequency: 0.01
          top_frequency: 0.1
        CerebrospinalFluid:
          erode_mask: Off
          extraction_resolution: 2
          include_delayed: On
          include_delayed_squared: On
          include_squared: On
          summary: Mean
        GlobalSignal:
          include_delayed: On
          include_delayed_squared: On
          include_squared: On
          summary: Mean
        Motion:
          include_delayed: On
          include_delayed_squared: On
          include_squared: On
        WhiteMatter:
          erode_mask: Off
          extraction_resolution: 2
          include_delayed: On
          include_delayed_squared: On
          include_squared: On
          summary: Mean
    lateral_ventricles_mask: $FSLDIR/data/atlases/HarvardOxford/HarvardOxford-lateral-ventricles-thr25-2mm.nii.gz

post_processing:
  spatial_smoothing:
    output:
      - smoothed
      - nonsmoothed
    smoothing_method:
      - FSL
    fwhm: [6]
  z-scoring:
    output:
      - z-scored

timeseries_extraction:

  run: Off

  # Enter paths to region-of-interest (ROI) NIFTI files (.nii or .nii.gz) to be used for time-series extraction, and then select which types of analyses to run.
  # Denote which analyses to run for each ROI path by listing the names below. For example, if you wish to run Avg and SpatialReg, you would enter: '/path/to/ROI.nii.gz': Avg, SpatialReg
  # available analyses:
  #   /path/to/atlas.nii.gz: Avg, Voxel, SpatialReg
  # tse_roi_paths:
  #  /ndmg_atlases/label/Human/Schaefer1000_space-MNI152NLin6_res-1x1x1.nii.gz: Avg
  #  /data3/autism_center/resources/cpac_resources/parc/Schaefer/Schaefer2018_400Parcels_17Networks_order_FSLMNI152_2mm.nii.gz
  #  /cpac_templates/Schaefer2018_space-FSLMNI152_res-2mm_desc-400Parcels17NetworksOrder.nii.gz: Avg
  #  /templates/Tian_Subcortex_S4_3T_1mm.nii.gz: Avg
  #  /templates/Buckner2011_7Networks_TightMask_parcels.nii.gz: Avg


  # Functional time-series and ROI realignment method: ['ROI_to_func'] or ['func_to_ROI']
  # 'ROI_to_func' will realign the atlas/ROI to functional space (fast)
  # 'func_to_ROI' will realign the functional time series to the atlas/ROI space
  #
  #     NOTE: in rare cases, realigning the ROI to the functional space may
  #           result in small misalignments for very small ROIs - please double
  #           check your data if you see issues
  #realignment: 'ROI_to_func'

  connectivity_matrix:
    # Create a connectivity matrix from timeseries data

    # Options:
    #  ['AFNI', 'Nilearn', 'ndmg']
    using:
      - Nilearn
    # Options:
    #  ['Pearson', 'Partial']
    # Note: These options are not configurable for ndmg, which will ignore these options
    measure:
      - Pearson
      - Partial

seed_based_correlation_analysis: 
  run: Off
  # SCA - Seed-Based Correlation Analysis
  # For each extracted ROI Average time series, CPAC will generate a whole-brain correlation map.
  # It should be noted that for a given seed/ROI, SCA maps for ROI Average time series will be the same.

amplitude_low_frequency_fluctuation: 
  run: Off
  # ALFF & f/ALFF
  # Calculate Amplitude of Low Frequency Fluctuations (ALFF) and and fractional ALFF (f/ALFF) for all voxels.

regional_homogeneity: 
  run: Off
  # ReHo
  # Calculate Regional Homogeneity (ReHo) for all voxels.

voxel_mirrored_homotopic_connectivity: 
  run: Off
  # VMHC
  # Calculate Voxel-mirrored Homotopic Connectivity (VMHC) for all voxels.

  symmetric_registration: 
    # Included as part of the 'Image Resource Files' package available on the Install page of the User Guide.
    # It is not necessary to change this path unless you intend to use a non-standard symmetric template.
    T1w_brain_template_symmetric: $FSLDIR/data/standard/MNI152_T1_${resolution_for_anat}_brain_symmetric.nii.gz

    # A reference symmetric brain template for resampling
    T1w_brain_template_symmetric_for_resample: $FSLDIR/data/standard/MNI152_T1_1mm_brain_symmetric.nii.gz

    # Included as part of the 'Image Resource Files' package available on the Install page of the User Guide.
    # It is not necessary to change this path unless you intend to use a non-standard symmetric template.
    T1w_template_symmetric: $FSLDIR/data/standard/MNI152_T1_${resolution_for_anat}_symmetric.nii.gz

    # A reference symmetric skull template for resampling
    T1w_template_symmetric_for_resample: $FSLDIR/data/standard/MNI152_T1_1mm_symmetric.nii.gz

    # Included as part of the 'Image Resource Files' package available on the Install page of the User Guide.
    # It is not necessary to change this path unless you intend to use a non-standard symmetric template.
    dilated_symmetric_brain_mask: $FSLDIR/data/standard/MNI152_T1_${resolution_for_anat}_brain_mask_symmetric_dil.nii.gz

    # A reference symmetric brain mask template for resampling
    dilated_symmetric_brain_mask_for_resample: $FSLDIR/data/standard/MNI152_T1_1mm_brain_mask_symmetric_dil.nii.gz

network_centrality:
  run: Off
 # Calculate Degree, Eigenvector Centrality, or Functional Connectivity Density.
 # Maximum amount of RAM (in GB) to be used when calculating Degree Centrality.
  # Calculating Eigenvector Centrality will require additional memory based on the size of the mask or number of ROI nodes.
  memory_allocation: 1.0
 # Full path to a NIFTI file describing the mask. Centrality will be calculated for all voxels within the mask.
  template_specification_file: /data3/autism_center/projects/awake_asleep/QC_PT/masks/used_group_cpac_MNI_mask_intersection_no30044_40perc.nii.gz
  degree_centrality:
   # Enable/Disable degree centrality by selecting the connectivity weights
    #   weight_options: ['Binarized', 'Weighted']
    # disable this type of centrality with:
    #   weight_options: []
    weight_options:
      - Binarized
      - Weighted
   # Select the type of threshold used when creating the degree centrality adjacency matrix.
    # options:
    #   'Significance threshold', 'Sparsity threshold', 'Correlation threshold'
    correlation_threshold_option: Sparsity threshold
   # Based on the Threshold Type selected above, enter a Threshold Value.
    # P-value for Significance Threshold
    # Sparsity value for Sparsity Threshold
    # Pearson's r value for Correlation Threshold
    correlation_threshold: 0.001
  eigenvector_centrality:
   # Enable/Disable eigenvector centrality by selecting the connectivity weights
    #   weight_options: ['Binarized', 'Weighted']
    # disable this type of centrality with:
    #   weight_options: []
    weight_options: []
   # Select the type of threshold used when creating the eigenvector centrality adjacency matrix.
    # options:
    #   'Significance threshold', 'Sparsity threshold', 'Correlation threshold'
    correlation_threshold_option: Sparsity threshold
   # Based on the Threshold Type selected above, enter a Threshold Value.
    # P-value for Significance Threshold
    # Sparsity value for Sparsity Threshold
    # Pearson's r value for Correlation Threshold
    correlation_threshold: 0.001
  local_functional_connectivity_density:
   # Enable/Disable lFCD by selecting the connectivity weights
    #   weight_options: ['Binarized', 'Weighted']
    # disable this type of centrality with:
    #   weight_options: []
    weight_options: []
   # Select the type of threshold used when creating the lFCD adjacency matrix.
    # options:
    #   'Significance threshold', 'Correlation threshold'
    correlation_threshold_option: Correlation threshold
   # Based on the Threshold Type selected above, enter a Threshold Value.
    # P-value for Significance Threshold
    # Sparsity value for Sparsity Threshold
    # Pearson's r value for Correlation Threshold
    correlation_threshold: 0.6

# PACKAGE INTEGRATIONS
# --------------------
PyPEER: 
  eye_mask_path: $FSLDIR/data/standard/MNI152_T1_${func_resolution}_eye_mask.nii.gz
  # Template-space eye mask
```
</details>

### Run command

```BASH
docker run \
  --user 0:0 \
  --security-opt=apparmor:unconfined \
  -i --rm \
  -v /data3/autism_center/wave2/QC/CPAC_1.8.4_36p:/scratch \
  -v /data3/autism_center/wave2/QC/CPAC_1.8.4_36p/out:/outputs \
  -v /data3/autism_center/wave2/QC/CPAC_1.8.4_36p/config:/config \
  -v /data3/autism_center/wave2/BIDS:/bids_dataset \
  fcpindi/c-pac:release-v1.8.4 /bids_dataset /outputs participant \
  --data_config_file /config/data_config_all.yml \
  --pipeline_file /config/pipeline_config_cpac_1.8.4_36P_motion_EDITED.yml \
  --save_working_dir \
  --tracking_opt-out \
  --n_cpus 4 \
  --mem_gb 10 \
  --bids_validator_config /config/bids_config.json \
  --participant_label 80003b 80011 80020 80023b 80024b 80026 80029 80030b 80037 80038 80039 80043 80044 80046 80048b 80049 80050 80053 80054 80058 80060 80061 80062 80064b 80065b 80070 80071 80072 80073 80074 80075b 80077 80078 80081 80084 80085 80086 80089 80090 80091c 80092 80093 80098 80100 80101 80103 80104 80105 80106b 80108 80109 80111 80112 80114 80115 80116 80117 80120 80123 80125 80127 80128 80130b 80131 80134 80135 80136 80138 80139 80140 80142 80143 80150 80153 80154 80155 80156 80158 80159 80160 80162 80163 80165 80166 80171 80172 80173b 80175 80176 80177 80178 80179 80180b 80181 80182 80183 80184 80186b 80191 80192 80194 80195 80196 80198 80199 80202b 80203c 80204 80205 80210 80211 80213 80215 80216 80217 80219 80220 80221 80222 80223 80224 80226 80228 80229 80232b 80233 80234 80235 80240 80242b 80243 80244 80248b 80251 80252b 80253 80256 80257 80258 80261 80263 80264b 80268 80270 80275 80276 80277 80278 80281 80282 80284 80285 80289 80292 80294 80297 80298 80299 80302 80304 80305 80307 80309 80328 80329 80331
```

### Expected behavior

Existing outputs / working directories don't cause subsequent runs to fail at `create_nuisance_regression_workflow`

### Acceptance criteria

- [ ] Existing outputs / working directories don't cause subsequent runs to fail at `create_nuisance_regression_workflow`

### C-PAC version

v1.8.4

### Container platform

Docker

### Docker and/or Singularity version(s)

Docker version 20.10.24+dfsg1, build 297e128

### Additional context

Removing the already-run participants from `--participant_label` avoids the issue
