### ISSUE TITLE
🐛 `[smoothed, unsmoothed]` not forking

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1988]
### Describe the bug

No `desc-sm` files are appearing in the output directory, and the `-NN_smooth 74` option for `3dSkullStrip` is the only smoothing shown in `pypeline.log` with `post_processing, spatial_smoothing, output: [smoothed, nonsmoothed]`

### Preconfig

- [ ] default
- [ ] abcd-options
- [ ] anat-only
- [ ] blank
- [ ] ccs-options
- [ ] fmriprep-options
- [ ] fx-options
- [ ] monkey
- [ ] monkey-ABCD
- [ ] ndmg
- [ ] nhp-macaque
- [ ] preproc
- [ ] rbc-options
- [ ] rodent

### Custom pipeline configuration

```YML
post_processing: 
 
  spatial_smoothing: 
 
    # Smooth the derivative outputs.
    # Set as ['nonsmoothed'] to disable smoothing. Set as ['smoothed', 'nonsmoothed'] to get both.
    #
    # Options:
    #     ['smoothed', 'nonsmoothed']
    output: [smoothed, nonsmoothed]
 
    # Tool to use for smoothing.
    # 'FSL' for FSL MultiImageMaths for FWHM provided
    # 'AFNI' for AFNI 3dBlurToFWHM for FWHM provided
    smoothing_method: [FSL]
```

### Expected behavior

Both smoothed and nonsmoothed outputs are generated, and clearly differentiated in their filenames

### Acceptance criteria

- [ ] Both smoothed and nonsmoothed outputs are generated
- [ ] Smoothed and nonsmoothed outputs are clearly differentiated in their filenames

### C-PAC version

v1.8.4 & v1.8.5

### Container platform

Docker

### Additional context

I created a https://github.com/FCP-INDI/C-PAC/labels/forking label in case any of these issues share a cause.
