### ISSUE TITLE
🐛 `FSLMerge`: `OSError: [Errno 7] Argument list too long: '/bin/sh'`

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#2006]
### Describe the bug

I believe the `$ARG_MAX` limit varies by system, but with long timeseries, where we split into individual timepoints in https://github.com/FCP-INDI/C-PAC/blob/de6407454d35e0cbf0434f7bc34fe44b924e2819/CPAC/registration/registration.py#L3844-L3847 and merge them back into a 4D image in https://github.com/FCP-INDI/C-PAC/blob/de6407454d35e0cbf0434f7bc34fe44b924e2819/CPAC/registration/registration.py#L3935-L3939, we can hit `OSError: [Errno 7] Argument list too long: '/bin/sh'`

Forcing relative paths via https://github.com/FCP-INDI/C-PAC/blob/2a9750c1a0075e5ba3f50ef3f54686d9357591b5/CPAC/utils/interfaces/fsl.py#L18-L25 was good enough to resolve the issue with the data I tested on brainlife.io, but users with ~2000 TR data are hitting the issue on bridges2

### To reproduce

Run a config with
```YAML
registration_workflows:
  functional_registration:
    func_registration_to_template:
      run: On
      apply_transform:
        using: abcd
```
with data with ~2000 timepoints

### Preconfig

- [ ] default
- [X] abcd-options
- [ ] anat-only
- [ ] blank
- [ ] ccs-options
- [ ] fmriprep-options
- [ ] fx-options
- [ ] monkey
- [ ] monkey-ABCD
- [ ] ndmg
- [ ] nhp-macaque
- [ ] preproc
- [ ] rbc-options
- [ ] rodent

### Custom pipeline configuration

```YML
registration_workflows:
  functional_registration:
    func_registration_to_template:
      run: On
      apply_transform:
        using: abcd
```

### Expected behavior

No crash

### Acceptance criteria

- [ ] C-PAC can recombine long timeseries into a 4D file regardless of system `$ARG_MAX`

### C-PAC version

v1.8.5

### Container platform

Singularity

### Additional context

A few ideas of how to tackle this, combining capital letters with capital Roman numerals:

### A. Check against `$ARG_MAX`

If the command length < `$ARG_MAX`, proceed as we have been. Otherwise, do one of these other things.

### B. Do other thing regardless of `$ARG_MAX`

Just have one way of merging that is robust to OS command length limitations and always do this method.

#### Ia. with `copyfile=False`

as suggested [here](https://github.com/nipy/nipype/issues/904#issuecomment-54015163)

#### Ib. `cd` into `mapflow` directory

The relative paths all go up a level and down into a nibling `mapflow` directory, like `../applywarp_func_to_standard_222_/mapflow/`. If we `cd` into that directory, we'd save ~33 characters per timepoint (I think _Ia_ would save the same)

#### IIa. `nibabel.funcs.concat_images`

as suggested [here](https://neurostars.org/t/fsl-merge-in-nipype-crashes-if-too-many-files/19986/4?u=shnizzedy) and [here](https://github.com/nipy/nipype/issues/904#issuecomment-298294138)

#### IIb. `nilearn.image.concat_imgs`

as suggested [here](https://github.com/nipy/nipype/issues/904#issuecomment-298294138)

---

I'm sure there are other ways around this too
