### ISSUE TITLE
✨ [User-requested Feature]

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#2175]
### Related problem

This conditional block https://github.com/FCP-INDI/C-PAC/blob/61ad414447023daf0e401a81c92267b09c64ed94/CPAC/registration/registration.py#L2309-L2325 seems to be conditioned on something spurious (https://github.com/FCP-INDI/C-PAC/blob/61ad414447023daf0e401a81c92267b09c64ed94/CPAC/registration/registration.py#L2310-L2313) to what the condition should actually be (https://github.com/FCP-INDI/C-PAC/blob/61ad414447023daf0e401a81c92267b09c64ed94/CPAC/resources/configs/pipeline_config_default.yml#L725-L726)

### Proposed feature

Update the condition to reflect the actual condition we should be checking, rather than a condition that probably corresponds to that condition.

### Acceptance criteria

- [ ] It's obvious which condition will be selected and why.

**Comment by shnizzedy** [comment]
I think we want to add something like

```YAML
pipeline_setup:
  # options: human, non-human primate, rodent
  organism: human
```

to the pipeline configuration and update https://github.com/FCP-INDI/C-PAC/blob/61ad414447023daf0e401a81c92267b09c64ed94/CPAC/registration/registration.py#L2309-L2314 to

```Python
    if cfg.pipeline_setup["organism"] != ["non-human primate"]:
```

, but I'm unsure:

* if `organism` is the key we want,
* if `human, non-human primate, rodent` is the controlled vocabulary we want or if we want to
  * also differentiate between children and adults (in humans and/or in other organisms), and/or
  * differentiate <span title="non-human primates">nhps</span> and rodents more specifically than that, or
* if we really need this information or if there's a simpler approach or refactor of the config to achieve the same clarity, or 
* what other places we want to use this option for a conditional instead of whatever's already there.

Also, the pipeline validation schema can be updated to make these https://github.com/FCP-INDI/C-PAC/blob/61ad414447023daf0e401a81c92267b09c64ed94/CPAC/pipeline/schema.py#L710-L711 required for <span title="non-human primate">nhp</span> pipelines (and these https://github.com/FCP-INDI/C-PAC/blob/61ad414447023daf0e401a81c92267b09c64ed94/CPAC/pipeline/schema.py#L694-L695 might be optional for <span title="non-human primate">nhp</span> pipelines? Or maybe all we need to do is get rid of the `FNIRT_T1w*` keys altogether and do

```YAML
registration_workflows:
  anatomical_registration:
    T1w_brain_template: /cpac_templates/MacaqueYerkes19_T1w_1.0mm_brain.nii.gz
    T1w_template: /cpac_templates/MacaqueYerkes19_T1w_1.0mm.nii.gz
```
in the <span title="non-human primate">nhp</span> pipelines?)
