### ISSUE TITLE
🔧 Add input field under `["registration_workflows", "functional_registration", "coregistration"]` to choose between whole head or brain

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#2203]
### Related problem

Related to #2174 by @sgiavasis 
Related to #2183 by @birajstha 
Related to https://github.com/FCP-INDI/C-PAC/pull/2183#discussion_r2014242448 by @shnizzedy 
Related to #2201 by @birajstha 

### Proposed feature

```YAML
registration_workflows:
  functional_registration:
    coregistration:

      # functional (BOLD/EPI) registration to anatomical (structural/T1)
      run: Off
      func_input_prep:

        # Choose whether to use the mean of the functional/EPI as the input to functional-to-anatomical registration or one of the volumes from the functional 4D timeseries that you choose.
        # input: ['Mean_Functional', 'Selected_Functional_Volume', 'fmriprep_reference']
        input: [Mean_Functional]
        Mean Functional:

          # Run ANTs’ N4 Bias Field Correction on the input BOLD (EPI)
          # this can increase tissue contrast which may improve registration quality in some data
          n4_correct_func: Off

        Selected Functional Volume:

          # Only for when 'Use as Functional-to-Anatomical Registration Input' is set to 'Selected Functional Volume'.
          #Input the index of which volume from the functional 4D timeseries input file you wish to use as the input for functional-to-anatomical registration.
          func_reg_input_volume: 0

        # Mask the sbref created by coregistration input prep nodeblocks above before registration
        mask_sbref: On

      boundary_based_registration:

        # this is a fork point
        #   run: [On, Off] - this will run both and fork the pipeline
        run: [Off]

        # reference for boundary based registration
        # options: 'whole-head' or 'brain'
        reference: whole-head

        # choose which FAST map to generate BBR WM mask
        # options: 'probability_map', 'partial_volume_map'
        bbr_wm_map: probability_map

        # optional FAST arguments to generate BBR WM mask
        bbr_wm_mask_args: -thr 0.5 -bin

        # Standard FSL 5.0 Scheduler used for Boundary Based Registration.
        # It is not necessary to change this path unless you intend to use non-standard MNI registration.
        bbr_schedule: $FSLDIR/etc/flirtsch/bbr.sch

      # Choose FSL or ABCD as coregistration method
      using: FSL

      #TODO Add input field here to choose between whole head or brain


      # Choose coregistration interpolation
      interpolation: trilinear

      # Choose coregistration cost function
      cost: corratio

      # Choose coregistration degree of freedom
      dof: 6

      # Extra arguments for FSL flirt
      arguments:
```

### Acceptance criteria

- [ ] <blockquote>leave it to the user to enable BOLD masking if they want a skull-stripped sbref</blockquote> ― @sgiavasis, https://github.com/FCP-INDI/C-PAC/issues/2174#issue-2810333063
