### ISSUE TITLE
✨ Add nodeblock descriptor yamls

### ISSUE THREAD

**Issue by tamsinrogers** [FCP-INDI/C-PAC#2205]
### Related problem

Nodeblock documentation currently lives in different places throughout the C-PAC codebase.  This feature will allow for a separation between the nodeblocks themselves and a user-friendly documentation resource, further upholding the SSOT goal driving the new docs.

### Proposed feature

Each nodeblock has a corresponding `.yml` descriptor file that follows this structure:

```
# This is a C-PAC nodeblock descriptor file.

Name:
    description:
    references:
    method:
            description:
            references:
            config:
            operations:
            source:
            validation:
```

New content: `operations` will include [Mermaid](https://mermaid.js.org/) syntax.  The new docs will read the descriptor yaml and pull this content into the the appropriate section of the website such that an accurate flowchart of the nodeblock can be visualized.

### Acceptance criteria

- [] each nodeblock has a corresponding `.yml` descriptor file
- [] the `operations` section of each nodeblock descriptor includes syntax that displays accurate Mermaid flowchart visualizing that nodeblock's behavior

### Alternatives

Flowcharts generally based on [C-PAC Lucid diagrams](https://lucid.app/documents#/documents?folder_id=215330788).

### Additional context

- Make additional sub-issues for each pre-processing step (as defined by C-PAC)
- Confirm that Mermaid-generated flowcharts provide an accurate representation of nodeblock behavior (can use the [Mermaid live editor](https://mermaid.live/edit#pako:eNpVjcFOg0AQhl9lMydNaEOhSLsHE0u1lyZ66EnoYQIDS4RdsiypFXh3Fxqjzmkm3_f_00OqMgIOeaUuqUBt2GmfSGbnKY6ELltTY3tmi8XjcCDDaiXpOrDd3UGxVqimKWVxf_N3k8Si_jhpxIwo5cd4Q9Gcf5U0sH18xMao5vyXnC5qYM9x-SZs_X8iNNnUS5wjz3GRomYR6lkBBwpdZsCN7siBmnSN0wn9RBMwgmpKgNs1oxy7yiSQyNHGGpTvStU_Sa26QoCtr1p7dU2GhvYlFhp_FZIZ6Uh10gAP5gbgPXwC99b-MgzdzWbthn6wdleeA1fgfrjc-mHgusFD4K88fzs68DX_dJebMBi_AdGedAc) for quick checking)

**Comment by tamsinrogers** [comment]
see 0d2153fb9b95e432e116c61eadf2dadfecbbc9b9, which initializes a descriptor `.yml` for `anat_preproc` and 896bb6fb13da90bcf8bd0e08429c4ae4993cee6b, which adds `Operations` content in the form of Mermaid syntax.  

**contents of `anat_preproc.yml`:**
> # This is a C-PAC nodeblock descriptor file.
> 
> Non-Local Means (NLM) Filtering:
>     description:
>         Performs non-local means filtering on structural data.
>     references:
>         https://en.wikipedia.org/wiki/Non-local_means
>     method:
>         nlm_filtering:
>             description:
>                 Uses ANTs DenoiseImage.
>             references:
>                 https://manpages.debian.org/experimental/ants/DenoiseImage.1.en.html
>             config:
>                 None
>             operations:
>                 graph TD;
>                     nlm_filtering["nlm_filtering"];
>                     anat_denoise["anat_denoise"];
>                     
>                     nlm_filtering -->|connects| anat_denoise;
>                     anat_denoise -->|output_image| desc_preproc_T1w["desc-preproc_T1w"];
>                     
>                     desc_preproc_input["desc-preproc_T1w"] -->|input data| nlm_filtering;
>                     nlm_filtering -->|outputs| desc_preproc_T1w;
>             source:
>                 NiWrap: https://github.com/childmindresearch/cpac_blocks/blob/main/anat_preproc/nlm.py
>                 Nipype: https://github.com/FCP-INDI/C-PAC/blob/rc/v1.8.7/CPAC/anat_preproc/anat_preproc.py#L1528-L1537
>             validation:
>                 s3://path/to/gold/standard
> 
> T1w Brain Mask Generation:
>     description:
>         Generates a binary brain mask of a T1w structural image.
>     references:
>         None
>     method:
>         brain_mask_fsl:
>             description:
>                 Uses FSL BET.
>             references:
>                 - links to manuals
>                 - links to papers
>                 - etc.
>             config:
>                 Robustfov: Off
>                 frac: 0.5
>                 mesh_boolean: Off
>                 outline: Off
>                 padding: Off
>                 radius: 0
>                 reduce_bias: Off
>                 remove_eyes: Off
>                 robust: Off
>                 skull: Off
>                 surfaces: Off
>                 threshold: Off
>                 vertical_gradient: 0.0
>             operations:
>                 graph TD;
>                     brain_mask_fsl["brain_mask_fsl"];
>                     fsl_brain_connector["fsl_brain_connector"];
> 
>                     desc_preproc_T1w["desc-preproc_T1w"] -->|input| brain_mask_fsl;
>                     brain_mask_fsl -->|calls| fsl_brain_connector;
>                     fsl_brain_connector -->|output| space_T1w_desc_brain_mask["space-T1w_desc-brain_mask"];
>             source:
>             validation:
>         brain_mask_afni:
>             description:
>                 Uses AFNI 3dSkullStrip.
>             references:
>                 - links to manuals
>                 - links to papers
>                 - etc.
>             config:
>                 shrink_factor: 0.6
>                 var_shrink_fac: On
>                 shrink_factor_bot_lim: 0.4
>                 avoid_vent: On
>                 n_iterations: 250
>                 pushout: On
>                 touchup: On
>                 fill_hole: 10
>                 NN_smooth: 72
>                 smooth_final: 20
>                 avoid_eyes: On
>                 use_edge: On
>                 exp_frac: 0.1
>                 push_to_edge: Off
>                 use_skull: Off
>                 perc_int: 0
>                 max_inter_iter: 4
>                 fac: 1
>                 blur_fwhm: 0
>                 monkey: Off
>             operations:
>                 graph TD;
>                     brain_mask_afni_T2["brain_mask_afni_T2"];
>                     afni_brain_connector["afni_brain_connector"];
> 
>                     desc_preproc_T2w["desc-preproc_T2w"] -->|input| brain_mask_afni_T2;
>                     brain_mask_afni_T2 -->|calls| afni_brain_connector;
>                     afni_brain_connector -->|output| space_T2w_desc_brain_mask["space-T2w_desc-brain_mask"];
>             source:
>             validation:
> 
> ACPC Alignment:
>     description:
>         ACPC alignment is meant to ... etc.
>     references:
>         - links to pages/tutorials generically about ACPC alignment
>     method:
>         acpc_alignment_head:
>             description:
>                 More specific info (if needed)
>             references:
>             config:
>             operations:
>                 graph TD;
>                     acpc_align_head["acpc_align_head"];
>                     acpc_alignment["acpc_alignment"];
> 
>                     desc_head_T1w["desc-head_T1w"] -->|input| acpc_align_head;
>                     desc_preproc_T1w["desc-preproc_T1w"] -->|input| acpc_align_head;
>                     T1w_ACPC_template["T1w-ACPC-template"] -->|template input| acpc_align_head;
> 
>                     acpc_align_head -->|calls| acpc_alignment;
> 
>                     acpc_alignment -->|output| desc_head_T1w_out["desc-head_T1w"];
>                     acpc_alignment -->|output| desc_preproc_T1w_out["desc-preproc_T1w"];
>                     acpc_alignment -->|output| from_T1w_to_ACPC_xfm["from-T1w_to-ACPC_mode-image_desc-aff2rig_xfm"];
>             source:
>             validation:
>         acpc_alignment_head_with_mask:
>             description:
>             references:
>             config:
>             operations:
>                 graph TD;
>                     acpc_align_head_with_mask["acpc_align_head_with_mask"];
>                     acpc_alignment["acpc_alignment"];
> 
>                     desc_head_T1w["desc-head_T1w"] -->|input| acpc_align_head_with_mask;
>                     desc_preproc_T1w["desc-preproc_T1w"] -->|input| acpc_align_head_with_mask;
>                     T1w_ACPC_template["T1w-ACPC-template"] -->|template input| acpc_align_head_with_mask;
>                     T1w_brain_ACPC_template["T1w-brain-ACPC-template"] -->|brain template input| acpc_align_head_with_mask;
>                     space_T1w_desc_brain_mask["space-T1w_desc-brain_mask"] -->|mask input| acpc_align_head_with_mask;
> 
>                     acpc_align_head_with_mask -->|calls| acpc_alignment;
> 
>                     acpc_alignment -->|output| desc_head_T1w_out["desc-head_T1w"];
>                     acpc_alignment -->|output| desc_preproc_T1w_out["desc-preproc_T1w"];
>                     acpc_alignment -->|output| space_T1w_desc_brain_mask_out["space-T1w_desc-brain_mask"];
>                     acpc_alignment -->|output| from_T1w_to_ACPC_xfm["from-T1w_to-ACPC_mode-image_desc-aff2rig_xfm"];
>             source:
>             validation:
> 

**generated Mermaid flowcharts:**
nlm_filtering:
<img width="291" alt="Image" src="https://github.com/user-attachments/assets/63064d26-d974-4532-aca3-bad8175918fb" />
brain_mask_fsl:
<img width="262" alt="Image" src="https://github.com/user-attachments/assets/427c3473-67d8-4229-b887-0b485f015569" />
brain_mask_afni:
<img width="292" alt="Image" src="https://github.com/user-attachments/assets/ac315006-cb84-4408-b5b5-d43edabb4bd0" />
acpc_alignment_head:
<img width="605" alt="Image" src="https://github.com/user-attachments/assets/dd71b747-3571-4bc5-8563-715f76b95b3a" />
acpc_alignment_head_with_mask:
<img width="715" alt="Image" src="https://github.com/user-attachments/assets/364f4b0b-1013-4bcb-be83-abdc68b4e939" />

good resources for this process: [BlockBuster](https://childmindresearch.github.io/blockbuster/) and [resource-inventory](https://childmindresearch.github.io/resource-inventory/).

**Comment by tamsinrogers** [comment]
I'll be working off of https://github.com/FCP-INDI/C-PAC/tree/new_docs to add these descriptor yamls.

**Comment by shnizzedy** [comment]
I think we should just list out [<span alt="BibTeX">$`{\mathrm{B{\scriptstyle{IB}} \! T\!_{\displaystyle E} \! X}}`$</span> citation-keys](https://www.bibtex.org/Format/) as the values for `references` keys and have a single <span alt="BibTeX">$`{\mathrm{B{\scriptstyle{IB}} \! T\!_{\displaystyle E} \! X}}`$</span> file (probably just move [`references.bib`](https://github.com/FCP-INDI/fcp-indi.github.io/blob/e7a92821729d8328c3e51918c5e91ca8c79123c7/docs/_sources/references/references.bib) from [:octocat:FCP-INDI/fcp-indi.github.io](https://github.com/FCP-INDI/fcp-indi.github.io) to this repo and update it as we go) that includes all of the relevant info for each reference. And we can choose a format to cite in the body of the description or methods ([sphinxcontrib-bibtex roles](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#roles-and-directives) or just the key in brackets or parentheses or some custom syntax) where we want/need to.

Related: https://github.com/FCP-INDI/cpac-docs/issues/3#issuecomment-2748669488

---

Since we're setting up something new, let's either use the officially-preferred `.yaml` extension instead of `.yml` or some new specific extension to be clear that these are C-PAC nodeblock descriptor YAMLs and not just any old YAMLs.

Related: https://github.com/childmindresearch/template-python-repository/issues/68

---

These will be nice not just for documentation, but also for validation. We can start with just
- [ ] requiring the descriptors exist,

and then later we can add checks that

- [ ] the inputs and outputs in the descriptors match those in the nodeblocks,
      and
- [ ] the internal calls and connections in the descriptors are present in the code.

---

I'm sure the descriptor syntax will become clearer with more examples, but I don't understand what goes in `config`. Depending on what all information goes into these descriptors, we could migrate the pipeline validation info from [its current Python-specific mega-schema](https://github.com/FCP-INDI/C-PAC/blob/386ba8e5c9b5816f4acada1b84ba8c4bbb2471d4/CPAC/pipeline/schema.py) into more modular (defined where they're used, viz., with the nodeblocks), more portable (e.g., JSON Schema, which we can write in YAML and use here, in the docs, and in the GUI) composable schemata.

Related: https://github.com/FCP-INDI/C-PAC_GUI/issues/97#issuecomment-1444150241

**Comment by shnizzedy** [comment]
In reading and responding to https://github.com/FCP-INDI/cpac-docs/issues/82 and https://github.com/FCP-INDI/cpac-docs/issues/81, it occurred to me that we could move all of the information from the NodeBlock decorators into the descriptors, like

https://github.com/FCP-INDI/C-PAC/blob/896bb6fb13da90bcf8bd0e08429c4ae4993cee6b/CPAC/anat_preproc/anat_preproc.yml#L3-L30 + https://github.com/FCP-INDI/C-PAC/blob/896bb6fb13da90bcf8bd0e08429c4ae4993cee6b/CPAC/anat_preproc/anat_preproc.py#L1711-L1720

could turn into something like

```YAML
Non-Local Means (NLM) Filtering:
  name: nlm_filtering
  switch:
    - - anatomical_preproc
      - non_local_means_filtering
      - run
    - - anatomical_preproc
      - run
  inputs:
    - desc-preproc_T1w
  outputs:
    - desc-preproc_T1w
  description: Performs non-local means filtering on structural data.
  references: https://en.wikipedia.org/wiki/Non-local_means
  method:
    nlm_filtering:
      description: Uses ANTs DenoiseImage.
      references: https://manpages.debian.org/experimental/ants/DenoiseImage.1.en.html
      config: None
      operations: >-
        graph TD; nlm_filtering["nlm_filtering"];
        anat_denoise["anat_denoise"];

        nlm_filtering -->|connects| anat_denoise; anat_denoise -->|output_image| desc_preproc_T1w["desc-preproc_T1w"];

        desc_preproc_input["desc-preproc_T1w"] -->|input data| nlm_filtering; nlm_filtering -->|outputs| desc_preproc_T1w;
      source:
        NiWrap: https://github.com/childmindresearch/cpac_blocks/blob/main/anat_preproc/nlm.py
        Nipype: https://github.com/FCP-INDI/C-PAC/blob/rc/v1.8.7/CPAC/anat_preproc/anat_preproc.py#L1528-L1537
      validation: s3://path/to/gold/standard
```

\+ 

```Python
@nodeblock
def non_local_means(wf, cfg, strat_pool, pipe_num, opt=None): 
```

(or depending how we go about https://github.com/FCP-INDI/cpac-docs/issues/82, something like `@nodeblock(Nipype)` instead of just `@nodeblock` for the decorator)

**Comment by sgiavasis** [comment]
Yes! The plan is to include the Inputs/Outputs in them at least. I didn't at first because:
1. We already have a nodeblock scraper in place, I wanted to avoid duplicating effort at first.
2. Pending on engine changes, at some point we'd like to change (or not change) how the inputs and outputs are formatted in these lists - so I didn't want to place them all until we make a decision or two regarding this.

One thing to consider is the possibility of having the nodeblocks also request specific meta-data from the original JSONs and also from newly created meta-data from preceding nodeblocks.

**Comment by sgiavasis** [comment]
Another requirement here that I forgot to emphasize:

- accomplish those above four requirements with a format that is naturalistic enough for external contributors to read and write into it without having to learn too-specific syntax

**Comment by shnizzedy** [comment]
> Another requirement here that I forgot to emphasize:
> 
> * accomplish those above four requirements with a format that is naturalistic enough for external contributors to read and write into it without having to learn too-specific syntax

Yeah, I was thinking the subschema model [here](https://github.com/FCP-INDI/cpac-docs/issues/81#issuecomment-2794586112) is probably too cumbersome for casual contributors, but I think having a separate schema for each reusable schema like this would be user-friendly enough to work.


For [this example](https://github.com/FCP-INDI/C-PAC/blob/new_docs/CPAC/distortion_correction/distortion_correction.yaml#L15-L25), I think the `config` in the descriptor could look something like

```YAML
config:
  fmap_skullstrip_option:
    description: Since the quality of the distortion heavily relies on the skull-stripping step, we provide a choice of method ('AFNI' for AFNI 3dSkullStrip or 'BET' for FSL BET).
    schema:
      type: string
      enum: [BET, AFNI]
    default: BET
  fmap_skullstrip_BET_frac:
    description: Set the fraction value for the skull-stripping of the magnitude file. Depending on the data, a tighter extraction may be necessary in order to prevent noisy voxels from interfering with preparing the field map.
    schema: /CPAC/schema/unitInterval
    default: 0.5
  fmap_skullstrip_AFNI_threshold:
    description: Set the threshold value for the skull-stripping of the magnitude file. Depending on the data, a tighter extraction may be necessary in order to prevent noisy voxels from interfering with preparing the field map.
    schema: /CPAC/schema/unitInterval
    default: 0.6
```

with

```YAML
$schema: "http://json-schema.org/draft-07/schema#"
$id: "/CPAC/schema/unitInterval"
description: any value between 0 and 1, inclusively
allOf:
  - type: number
  - minumum: 0
  - maximum: 1
```

in `CPAC/schema/unitInterval`.

(I like that this example has a one-off schema for `fmap_skullstrip_option` and a reusable schema for `fmap_skullstrip_BET_frac` and `fmap_skullstrip_AFNI_threshold`. In practice, we can also convert one-off schemas to reusable ones or vice-versa as needed.)
