### ISSUE TITLE
🐛 'Configuration' object has no attribute 'subject_id'

### ISSUE THREAD

**Issue by birajstha** [FCP-INDI/C-PAC#2254]
### Describe the bug

Following error occurred while running longitudinal pipeline.

```python
Traceback (most recent call last):
  File "/code/CPAC/_entrypoints/run.py", line 963, in <module>
    raise exception
  File "/code/CPAC/_entrypoints/run.py", line 953, in <module>
    run_main()
  File "/code/CPAC/_entrypoints/run.py", line 921, in run_main
    exitcode = CPAC.pipeline.cpac_runner.run(
  File "/code/CPAC/pipeline/cpac_runner.py", line 497, in run
    run_T1w_longitudinal(sublist, c)
  File "/code/CPAC/pipeline/cpac_runner.py", line 249, in run_T1w_longitudinal
    anat_longitudinal_wf(subject_id, sub_list, cfg)
  File "/code/CPAC/longitudinal_pipeline/longitudinal_workflow.py", line 440, in anat_longitudinal_wf
    rpool.gather_pipes(workflow, config)
  File "/code/CPAC/pipeline/engine.py", line 1115, in gather_pipes
    outputs_logger = getLogger(f'{cfg["subject_id"]}_expectedOutputs')
  File "/code/CPAC/utils/configuration/configuration.py", line 203, in __getitem__
    return getattr(self, key)
AttributeError: 'Configuration' object has no attribute 'subject_id'
```

### Preconfig

- [ ] default
- [ ] abcd-options
- [ ] anat-only
- [ ] blank
- [ ] ccs-options
- [ ] fmriprep-options
- [ ] fx-options
- [ ] monkey
- [ ] monkey-ABCD
- [ ] ndmg
- [ ] nhp-macaque
- [ ] preproc
- [ ] rbc-options
- [ ] rodent

### Custom pipeline configuration

```YML
FROM: default

pipeline_setup:
  pipeline_name: longitudinal-test
  desired_orientation: RPI
  output_directory:
    quality_control:
      generate_quality_control_images: Off
longitudinal_template_generation:
  run: On
  # using: C-PAC legacy
registration_workflows:
  anatomical_registration:
    registration:
      using:
        - ANTS
        # - FSL
      # option parameters
      ANTs:
        # If a lesion mask is available for a T1w image, use it to improve the ANTs' registration
        # ANTS registration only.
        use_lesion_mask: Off

        # ANTs parameters for T1-template-based registration
        T1_registration:
          - float: 1
          - collapse-output-transforms: 0
          - dimensionality: 3
          - initial-moving-transform:
              initializationFeature: 0
          - transforms:
            - Rigid:
                gradientStep: 0.1
                metric:
                  type: MI
                  metricWeight: 1
                  numberOfBins: 32
                  samplingStrategy: Regular
                  samplingPercentage: 0.25
                convergence:
                  iteration: 1000x500x250x100
                  convergenceThreshold: 1e-08
                  convergenceWindowSize: 10
                smoothing-sigmas: 3.0x2.0x1.0x0.0
                shrink-factors: 8x4x2x1
                use-histogram-matching: On
            - Affine:
                gradientStep: 0.1
                metric:
                  type: MI
                  metricWeight: 1
                  numberOfBins: 32
                  samplingStrategy: Regular
                  samplingPercentage: 0.25
                convergence:
                  iteration: 1000x500x250x100
                  convergenceThreshold: 1e-08
                  convergenceWindowSize: 10
                smoothing-sigmas: 3.0x2.0x1.0x0.0
                shrink-factors: 8x4x2x1
                use-histogram-matching: On
            - SyN:
                gradientStep: 0.1
                updateFieldVarianceInVoxelSpace: 3.0
                totalFieldVarianceInVoxelSpace: 0.0
                metric:
                  type: CC
                  metricWeight: 1
                  radius: 4
                convergence:
                  iteration: 100x100x70x20
                  convergenceThreshold: 1e-09
                  convergenceWindowSize: 15
                smoothing-sigmas: 3.0x2.0x1.0x0.0
                shrink-factors: 6x4x2x1
                use-histogram-matching: On
                winsorize-image-intensities:
                  lowerQuantile: 0.01
                  upperQuantile: 0.99
nuisance_corrections:
  2-nuisance_regression:
    run: [Off]
    create_regressors: Off
functional_preproc:
  run: On
  update_header:
    run: On
  slice_timing_correction:
    run: [Off]
  motion_estimates_and_correction:
    run: Off
  distortion_correction:
    run: [Off]
  func_masking:
    run: On
  generate_func_mean:
    run: On
  normalize_func:
    run: Off
  scaling:
    run: Off
  despiking:
    run: [Off]
  coreg_prep:
    run: On
timeseries_extraction:
  run: Off
amplitude_low_frequency_fluctuation:
  run: Off
regional_homogeneity:
  run: Off
voxel_mirrored_homotopic_connectivity:
  run: On
network_centrality:
  run: Off
```

### Run command

```BASH
#!/bin/bash
#SBATCH -N 1
#SBATCH -p RM-shared
#SBATCH -t 60:00:00
#SBATCH --ntasks-per-node=8

MED=/ocean/projects/med250004p
DATA=s3://fcp-indi/data/Projects/CORR/RawDataBIDS
OUTPUT=/ocean/projects/med250004p/bshresth/projects/longitudinalPipeline/outputs
IMAGE=/ocean/projects/med250004p/bshresth/projects/cpac.sif

PIPELINE=/ocean/projects/med250004p/bshresth/projects/longitudinalPipeline/pipelines/lp1.yml

site=Utah_2
subject=sub-0026017

repo=/ocean/projects/med250004p/bshresth/projects/2223/C-PAC
singularity run \
    -B ${repo}/CPAC:/code/CPAC \
    -B $MED \
    -B $OUTPUT:$OUTPUT $IMAGE $DATA/$site $OUTPUT participant \
    --num_ants_threads 1 \
    --skip_bids_validator \
    --n_cpus 1 \
    --mem_gb 34 \
    --pipeline_file $PIPELINE \
    --participant_label $subject
```

### Expected behavior

Runs without error

### Acceptance criteria

Run with error
