### ISSUE TITLE
🐛 No 'Run Complete' message — CPAC exits without errors or warnings

### ISSUE THREAD

**Issue by birajstha** [FCP-INDI/C-PAC#2259]
### Describe the bug

All expected outputs are found in the outputs dir but, CPAC exits without writing "CPAC run complete" message to the log.

Expected outputs from log
```YAML
anat:
- sub-NDARINV003RTV85*_ses-baselineYear1Arm1*_desc-ABCDpreproc*_T1w*
- sub-NDARINV003RTV85*_ses-baselineYear1Arm1*_desc-head*_T1w*
- sub-NDARINV003RTV85*_ses-baselineYear1Arm1*_desc-preproc*_T1w*
- sub-NDARINV003RTV85*_ses-baselineYear1Arm1*_desc-restore*_T1w*
- sub-NDARINV003RTV85*_ses-baselineYear1Arm1*_desc-restoreBrain*_T1w*
```

Outputs in output/anat dir
```BASH
ls /ocean/projects/med250004p/bshresth/projects/surface_pipelines/outputs/output/pipeline_pipeline1/sub-NDARINV003RTV85/ses-baselineYear1Arm1/anat
sub-NDARINV003RTV85_ses-baselineYear1Arm1_desc-ABCDpreproc_T1w.json
sub-NDARINV003RTV85_ses-baselineYear1Arm1_desc-ABCDpreproc_T1w.nii.gz
sub-NDARINV003RTV85_ses-baselineYear1Arm1_desc-head_T1w.json
sub-NDARINV003RTV85_ses-baselineYear1Arm1_desc-head_T1w.nii.gz
sub-NDARINV003RTV85_ses-baselineYear1Arm1_desc-preproc_T1w.json
sub-NDARINV003RTV85_ses-baselineYear1Arm1_desc-preproc_T1w.nii.gz
sub-NDARINV003RTV85_ses-baselineYear1Arm1_desc-restoreBrain_T1w.json
sub-NDARINV003RTV85_ses-baselineYear1Arm1_desc-restoreBrain_T1w.nii.gz
sub-NDARINV003RTV85_ses-baselineYear1Arm1_desc-restore_T1w.json
sub-NDARINV003RTV85_ses-baselineYear1Arm1_desc-restore_T1w.nii.gz
```

### Preconfig

- [ ] default
- [ ] abcd-options
- [ ] anat-only
- [ ] blank
- [ ] ccs-options
- [ ] fmriprep-options
- [ ] fx-options
- [ ] monkey
- [ ] monkey-ABCD
- [ ] ndmg
- [ ] nhp-macaque
- [ ] preproc
- [ ] rbc-options
- [ ] rodent

### Custom pipeline configuration

```YAML

%YAML 1.1
---
FROM: abcd-prep
pipeline_setup:
  pipeline_name: pipeline1
  output_directory:
    quality_control:
      generate_xcpqc_files: Off
  system_config:
    maximum_memory_per_participant: 10.0
    random_seed: 1
    raise_insufficient: Off

surface_analysis:
  abcd_prefreesurfer_prep:
    run: On

anatomical_preproc:
  run: On
  acpc_alignment:
    run: Off
    run_before_preproc: Off

  brain_extraction:
    run: Off
    using: [FreeSurfer-ABCD]

  non_local_means_filtering:
    run: [Off]

  n4_bias_field_correction:
    run: [Off]

registration_workflows:
  anatomical_registration:
    run: Off

  functional_registration:
    coregistration:
      run: Off
      

functional_preproc:
  run: Off

```

### Run command

```BASH
#!/bin/bash
#SBATCH -N 1
#SBATCH -p RM-shared
#SBATCH -t 60:00:00
#SBATCH --ntasks-per-node=2

MED=/ocean/projects/med250004p
DATA=/ocean/projects/med250004p/bshresth/projects/data
OUTPUT=/ocean/projects/med250004p/bshresth/projects/surface_pipelines/outputs
IMAGE=/ocean/projects/med250004p/bshresth/projects/c-pac_nightly.sif

PIPELINE=/ocean/projects/med250004p/bshresth/projects/surface_pipelines/pipelines/pipeline1.yml

subject=sub-NDARINV003RTV85

repo=/ocean/projects/med250004p/bshresth/projects/C-PAC
singularity run \
    -B ${repo}/CPAC:/code/CPAC\
    -B $MED \
    -B $DATA:$DATA \
    -B $OUTPUT:$OUTPUT $IMAGE $DATA $OUTPUT participant \
    --num_ants_threads 1 \
    --skip_bids_validator \
    --n_cpus 2 \
    --mem_gb 14 \
    --pipeline_file $PIPELINE \
    --participant_label $subject
```

### Expected behavior

CPAC run complete message in the log

### Acceptance criteria

Run completed or error logged 

### Screenshots

![Image](https://github.com/user-attachments/assets/a796324e-368d-441d-a005-0865b2d174bc)
