### ISSUE TITLE
✨ All-switches-OFF pre-config

### ISSUE THREAD

**Issue by birajstha** [FCP-INDI/C-PAC#2260]
### Related problem

When running tests for some configs, I imagined it would make a lot of sense to have a pre-config like `blank` or `default` but with all the switches OFF. This would allow us to pick and turn only the particular switches instead of finding which ones are on and turning each OFF.
for eg.

```YAML
FROM: abcd-prep
surface_analysis:
  abcd_prefreesurfer_prep:
    run: On

anatomical_preproc:
  run: On
  acpc_alignment:
    run: Off
    run_before_preproc: Off

  brain_extraction:
    run: Off
    using: [FreeSurfer-ABCD]

  non_local_means_filtering:
    run: [Off]

  n4_bias_field_correction:
    run: [Off]

registration_workflows:
  anatomical_registration:
    run: Off

  functional_registration:
    coregistration:
      run: Off
      

functional_preproc:
  run: Off

```
### Proposed feature

Make a pre-config just like `blank` or `default` but with all switches OFF. 

### Acceptance criteria

All switches off pre-config and can be expanded upon like below

```YAML
FROM: All-OFF #or any other better name here

surface_analysis:
  abcd_prefreesurfer_prep:
    run: On
anatomical_preproc:
  run: On
```
and this would only enable those nodeblock.
