### ISSUE TITLE
subject list make scanning params seperate for each func

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#562]
this can be done with a nested dictionary, i.e.

```
rest:
    rest_1_rest:
           filepath: data/sub1/func/rest1.nii.gz
           scan_params: { TR: 2.5, slice_acq: seq+z}
    rest_2_rest:
           filepath: data/sub1/func/rest2.nii.gz
           scan_params: { TR: .645, slice_acq: seq+z}
```
